name: Build & publish bleeding-edge Docker image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build and publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kdrag0n/pyrobud:unstable
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
